version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: aostore-openspeedtest_web_1
      APP_PORT: 3000

  web:
    image: openspeedtest/latest:v2.0.6@sha256:a6a7e3b3e9e93cfe7b9b2eb49c60b2a93644149a0a600845d4df57148b193ff6
    restart: on-failure
